export const plans = [
    {
        title: "G-Basic",
        monthlyPrice: 6,
        quarterlyPrice: 18,
        yearlyPrice: 72,
        yearlyPriceNgn: 65294,
        quarterlyPriceNgn: 15000,
        monthlyPriceNgn: 5000,
        monthlySavePercent: 0,
        quarterlySavePercent: 5,
        yearlySavePercent: 15,
        description: "Upgrade today for amazing exclusive offers.",
        features: [
            {
                text: "Infinite Chatting",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Text Editing",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Image Generation-5 images monthly",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Social Media Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Assessment Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Short Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Comprehensive Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Learning Material Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Downloadable Content",
                includedMonthly: true,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Learning & Development Portal access",
                includedMonthly: true,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "E-mail support",
                includedMonthly: true,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Slide Maker",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Invite team",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Content translator",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Article writer",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Letter writer",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Save to Gmind Drive",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Humanizer",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Speech to Text",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
        ],
        actionLabel: "Choose Plan",
    },
    {
        title: "G-Premium",
        monthlyPrice: 9,
        quarterlyPrice: 27,
        yearlyPrice: 108,
        yearlyPriceNgn: 90000,
        quarterlyPriceNgn: 22500,
        monthlyPriceNgn: 7500,
        monthlySavePercent: 0,
        quarterlySavePercent: 5,
        yearlySavePercent: 15,
        description: "Upgrade today for amazing exclusive offers.",
        features: [
            {
                text: "Infinite Chatting",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Text Editing",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Image Generation-5 images monthly",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Social Media Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Assessment Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Short Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Comprehensive Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Learning Material Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Downloadable Content",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Learning & Development Portal access",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "E-mail support",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Slide Maker",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Invite team",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Content translator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Article writer",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Letter writer",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Save to Gmind Drive",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Humanizer",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
            {
                text: "Speech to Text",
                includedMonthly: false,
                includedQuarterly: false,
                includedYearly: false,
            },
        ],
        actionLabel: "Choose Plan",
        popular: true,
    },
    {
        title: "G-Advance",
        monthlyPrice: 11,
        quarterlyPrice: 33,
        yearlyPrice: 132,
        yearlyPriceNgn: 120000,
        quarterlyPriceNgn: 30000,
        monthlyPriceNgn: 10000,
        monthlySavePercent: 0,
        quarterlySavePercent: 5,
        yearlySavePercent: 15,
        description: "Upgrade today for amazing exclusive offers.",
        features: [
            {
                text: "Infinite Chatting",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Text Editing",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Image Generation-5 images monthly",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Social Media Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Assessment Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Short Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Comprehensive Content Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Learning Material Generator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Downloadable Content",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Learning & Development Portal access",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "E-mail support",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Slide Maker",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Invite team",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Content translator",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Article writer",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Letter writer",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Save to Gmind Drive",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Humanizer",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
            {
                text: "Speech to Text",
                includedMonthly: true,
                includedQuarterly: true,
                includedYearly: true,
            },
        ],
        actionLabel: "Choose Plan",
    },
];